name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-macos:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: install fakechroot
      run: brew install ./macos/fakechroot.rb
    - name: install dependencies
      run: brew install gperftools
    - name: make
      run: make
    - name: make check
      run: make check
  build-win:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt -y install clang clang-tools python fakechroot libgoogle-perftools-dev google-perftools
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make analyze
      run: make analyze
